  - name: ensure apt cache is up to date
    action: apt update_cache=yes

  - name: install ntp
    apt: name=ntp state=latest
    tags: ntp

  - name: set NTP config
    template: src=ntp.conf.j2 dest=/etc/ntp.conf
    tags: ntp
    notify:
    - restart ntp

  - name: install git
    apt: name=git state=latest
    tags: git