  - name: Join Domain
    win_domainjoin:
        domainname: "trondcloud.hindenes.com"
        domainusername: "thadministrator@trondcloud.hindenes.com"
        domainpassword: "Password123456"
        OUPath: "OU=servers,DC=trondcloud,DC=hindenes,DC=com"
        restart: yes
