  - name: Test Windows
    action: win_ping

# Download Wep PI if it's not already on disk
  - name: Verify Web PI
    action: win_stat path="C:\WebPI.msi"
    register: WinPiFile

  - name: Download Wep PI
    action: win_get_url dest="C:\WebPI.msi" url="http://download.microsoft.com/download/C/F/F/CFF3A0B8-99D4-41A2-AE1A-496C08BEB904/WebPlatformInstaller_amd64_en-US.msi"
    when: WinPiFile.stat.exists == false


# Installed Web PI if not already there
  - name: Check if Wep PI is installed
    action: win_stat path="C:\Program Files\Microsoft\Web Platform Installer\WebPlatformInstaller.exe"
    register: WinPiInstalledFile

  - name: Install Web PI
    action: win_msi path="C:\WebPI.msi" creates="C:\Program Files\Microsoft\Web Platform Installer\WebPlatformInstaller.exe"
    when: WinPiInstalledFile.stat.exists == false

  - name: Configure IIS+PHP
    action: script WebPI-IIS-PHP.ps1

# Download the WP package if it isnt already there
  - name: Verify Web PI
    action: win_stat path="C:\wordpress{{ wordpress_desired_version }}.zip"
    register: WpZipFile

  - name: Download wordpress
    action: win_get_url dest "C:\wordpress{{ wordpress_desired_version }}.zip" url="http://wordpress.org/wordpress-{{ wordpress_desired_version }}-IIS.zip"
    when: WpZipFile.stat.exists == false