##
    # Wordpress
    #


    #- name: Clone wordpress
    #  subversion: repo=http://core.svn.wordpress.org/tags/$wordpress_version dest=/var/www/wordpress
    #  tags: wordpress
    #  register: gitclonewordpressresult
    #  ignore_errors: True
    #  notify: 
    #  - restart apache2


    # - debug: msg="hostvars is {{ hostvars[groups['tag_Group_MySQL'][0]]  }}"
    # - debug: msg="hostvars is {{ hostvars[groups['tag_Group_MySQL'][0]] | to_yaml }}"
    # - debug: msg="hostvars is {{ hostvars[groups['tag_Group_MySQL'][0]] | to_json }}"

    # - name: debug 1
    #   debug: msg="hostvars is {{ hostvars[groups['tag_Group_MySQL'][0]][ansible_default_ipv4.adress] }}"
    #   ignore_errors: yes

    # - name: debug 2
    #   debug: msg="hostvars is {{ hostvars[groups['tag_Group_MySQL'][0]]['ansible_default_ipv4.adress'] }}"
    #   ignore_errors: yes

    # - name: debug 3
    #   debug: msg="hostvars is {{ hostvars[groups['tag_Group_MySQL'][0]]['ansible_default_ipv4'] }}"
    #   ignore_errors: yes

    # - name: debug 4
    #   debug: msg="hostvars is {{ hostvars[groups['tag_Group_MySQL'][0]][ansible_all_ipv4_addresses] }}"
    #   ignore_errors: yes
    - debug: msg="hostvars is {{ hostvars[groups['tag_Group_MySQL'][0]]  }}"

    - name: var1
      template: src=var1.txt.j2 dest=/tmp/var1.txt
      ignore_errors: yes

    - name: var2
      template: src=var2.txt.j2 dest=/tmp/var2.txt
      ignore_errors: yes

