    - name: Install required packages.
      action: apt pkg={{ item }} state=installed
      with_items:
        - python-mysqldb
        - mysql-server
        - mysql-client

    - name: Ensure MySQL server is running
      action: service name=mysql state=started

    - name: Configuration file, my.cnf
      action: template src=etc-mysql-my-cnf.j2 dest=/etc/mysql/my.cnf
      tags: common
      notify: 
      - restart mysql

    - include: mysql-secure.yml